# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

collections:

  - name: "community.docker"
    version: "3.2.1"

roles:

  - name: "geerlingguy.docker"
    version: "6.0.4"

  - name: "geerlingguy.pip"
    version: "2.2.0"

...
