# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Get stats of RSD working directory"
  ansible.builtin.stat:
    path: "{{ rsd_working_directory }}"
  register: "working_directory"

- name: "Determine if this is an initial dry-run"
  ansible.builtin.set_fact:
    is_initial_dryrun: "{{ ansible_check_mode and not working_directory.stat.exists }}"

- name: "Check for python modules"
  community.general.python_requirements_info:
    dependencies: "{{ rsd_dependencies }}"
  register: "python_requirements"

- name: "Assert that required python modules are available"
  ansible.builtin.assert:  # noqa ignore-errors
    that:
      - "item in python_requirements.valid"
    fail_msg: "Python module '{{ item }}' is missing!"
  loop: "{{ rsd_dependencies }}"
  ignore_errors: "{{ is_initial_dryrun }}"

- name: "Get stats of TLS certificate"
  ansible.builtin.stat:
    path: "{{ rsd_tls_cert_path }}"
  register: "tls_cert"

- name: "Get stats of TLS private key"
  ansible.builtin.stat:
    path: "{{ rsd_tls_key_path }}"
  register: "tls_key"

- name: "Assert that required TLS files are present"
  ansible.builtin.assert:  # noqa ignore-errors
    that:
      - "tls_cert.stat.exists"
      - "tls_key.stat.exists"
    fail_msg: "TLS certificate and/or private key missing!"
  ignore_errors: "{{ is_initial_dryrun }}"

- name: "Get stats of DH parameters file"
  ansible.builtin.stat:
    path: "{{ rsd_nginx_dhparam_file_path }}"
  register: "dhparam_file"

- name: "Determine if DH parameters file needs to be created"
  ansible.builtin.set_fact:
    create_dhparam_file: "{{ not dhparam_file.stat.exists }}"

...
