# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: "galaxy"
  options:
    role-file: "requirements.yml"
    requirements-file: "requirements.yml"
driver:
  name: "podman"
platforms:
  - name: "instancersd"
    image: "${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:22.04}"
    pre_build_image: true
    override_command: false
    privileged: true  # Required to run Docker in Podman
    systemd: true
    tty: true
lint: |
  yamllint --strict --format colored . &&
  ansible-lint -v --force-color --offline .
provisioner:
  name: "ansible"
  config_options:
    defaults:
      stdout_callback: "yaml"
      bin_ansible_callbacks: true
  inventory:
    hosts:
      all:
        vars:
          pip_install_packages:
            - name: "docker"
    host_vars:
      instancersd:
        tls_cert_file: "{{ (lookup('env', 'MOLECULE_SCENARIO_DIRECTORY'), 'test.pem') | path_join }}"
        tls_key_file: "{{ (lookup('env', 'MOLECULE_SCENARIO_DIRECTORY'), 'test.key') | path_join }}"
        nginx_dhparam_file: "{{ (lookup('env', 'MOLECULE_SCENARIO_DIRECTORY'), 'dhparam.pem') | path_join }}"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "lint"
    - "cleanup"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "check"
    - "converge"
    - "idempotence"
    - "side_effect"
    - "verify"
    - "cleanup"
    - "destroy"

...
