# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: "Prepare"
  hosts: "all"
  vars:
    docker_daemon_options:
      storage-driver: "vfs"
    pip_install_packages:
      - name: "docker"
      - name: "docker-compose"
  tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      when: "ansible_os_family == 'Debian'"

    - name: "Apply geerlingguy.pip role"
      ansible.builtin.include_role:
        name: "geerlingguy.pip"

    - name: "Apply geerlingguy.docker role"
      ansible.builtin.include_role:
        name: "geerlingguy.docker"

    - name: "Copy TLS files"
      ansible.builtin.copy:
        src: "{{ item.file }}"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - { file: "{{ tls_cert_file }}", dest: "{{ rsd_tls_cert_path }}", mode: "0644" }
        - { file: "{{ tls_key_file }}", dest: "{{ rsd_tls_key_path }}", mode: "0600" }
        - { file: "{{ nginx_dhparam_file }}", dest: "{{ rsd_nginx_dhparam_file_path }}", mode: "0600" }
      no_log: True